language: node_js
node_js:
  - "14"

addons:
  chrome: stable

script: 
  - yarn run test-ci
  - NO_BUNDLE=true yarn run test-ci

after_script:
  - find ./coverage/HeadlessChrome* -name "lcov.info" -exec cat {} \; | coveralls
